defaults: &defaults
  working_directory: ~/PocketWatchCoppaHook-Android
  docker:
    - image: circleci/android:api-28
      environment:
        CIRCLE_ARTIFACTS: /tmp/circleci-artifacts
        CIRCLE_TEST_REPORTS: /tmp/circleci-test-results
        GRADLE_OPTS: '-Dorg.gradle.jvmargs="-Xmx6144M -XX:MaxPermSize=1024m -Xms512m -XX:+HeapDumpOnOutOfMemoryError"'

version: 2
jobs:
  test:
    <<: *defaults
    resource_class: large

    steps:
      - checkout

      - run:
          name: Create Directory
          command:  mkdir -p $CIRCLE_ARTIFACTS $CIRCLE_TEST_REPORTS

      - run:
          name: Git Submodule Update
          command:  git submodule update --init --recursive

      - restore_cache:
          key: gradle-cache-v1-{{ checksum "build.gradle" }}

      - run:
          name: Download Android Dependencies
          command: ./gradlew androidDependencies

      - save_cache:
          paths:
            - ~/.gradle
          key: gradle-cache-v1-{{ checksum "build.gradle" }}

      - run:
          name: Run Tests
          command: ./gradlew test

      - store_test_results:
          path: $CIRCLE_TEST_REPORTS

      - store_artifacts:
          path: $CIRCLE_ARTIFACTS

  deploy:
    <<: *defaults
    steps:
      - checkout

      - restore_cache:
          key: gradle-cache-v1-{{ checksum "build.gradle" }}

      - run:
          name: Build release package
          command: ./gradlew assembleRelease

      - run:
          name: Deploy to Bintray
          command: ./gradlew pocket_watch-hook-plugin:bintrayUpload

workflows:
  version: 2
  test-n-deploy:
    jobs:
      # Execute job for all branches, and all tags.
      - test:
          filters:
            tags:
              only: /.*/

      # Execute job for no branches and all tags.
      - deploy:
          requires:
            - test
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
